spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

app:
  jwt:
    secret: thisisverysecret
    issuer: Java Five
    expiresAfterDays: 30

server:
  port: 8000