spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

server:
  port: 8000